# Connection Pool, javax.mail
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
      #jdbc-url: jdbc:log4jdbc:oracle:thin:192.168.0.214:1521:xe
      username: ENC(wyGJ+AyHooFqMR9OhBAxww==)
      #username: ENC(pyEdsFtV0oGCohJT/MJs9Q==)
      password: ENC(MZnEBe2GOAuE5aR0P/shog==)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(obt3sH4uW/Aw7joeRGQGWiccwRN27sN+wJWIKsj4hvs=)
    password: ENC(Yn98euTftvWuMJBeyHxgpqj/Rax91BooCAoOhhDHvH8=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# main:
#    web-application-type: none  # Do not use embeded tomcat

# mybatis
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml

# character encoding, session, port
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800
      tracking-modes: cookie
  port: 8080

# jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor